name: foody
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  inspection: ^0.0.13
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  location: ^5.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  timelines: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#FE724C"
  image: assets/logo/splash_logo.png

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/restaurants/
    - assets/fonts/
    - assets/icons/
    - assets/logo/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/Sofia_Pro_Medium.otf
          weight: 500
        - asset: assets/fonts/Sofia_Pro_Regular.otf
          weight: 300
        - asset: assets/fonts/Sofia_Pro_Semi_Bold.otf
          weight: 700
        - asset: assets/fonts/Sofia_Pro_Bold.otf
          weight: 900
